config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  post '/home/guess', to: 'home#guess'
  resources :challenges, only: [:show, :index, :update]
  resources :quests, only: [:index, :create]
  resources :quest2, only: [:index, :create]
  resources :youdidit, only: [:index]
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/challenge.rb
class Challenge < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  layout 'challenge'

  def show
    @challenge = Challenge.find_by(url: params[:id])
  end

  def update
    @challenge = Challenge.find_by(url: params['id'])

    if params['resposta'].upcase == @challenge.password.upcase
      @challenge.count += 1
      @challenge.save

      if @challenge.password == '30'
        @final = Challenge.find_by(url: 'youdidit')
        @final.count += 1
        @final.save

        redirect_to youdidit_index_path
      else
        redirect_to challenge_path(@challenge.redirect_url)
      end
    else
      render :show
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @challenge = Challenge.find_by(url: 'inicio')
  end

  def guess
    @challenge = Challenge.find_by(id: params['id'])

    if params['resposta'].upcase == @challenge.password.upcase
      @challenge.count += 1
      @challenge.save

      redirect_to challenge_path(@challenge.redirect_url)
    else
      render :index
    end
  end
end

app/controllers/quest2_controller.rb
class Quest2Controller < ApplicationController
  def index
  end

  def post
  end
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  def index
    response.headers["X-Frame-Options"] = "ALLOW-FROM http://google.com"
  end

  def create
    if params[:resposta] == 'pinguim'
      redirect_to quest2_index_path
    end
  end
end

app/controllers/youdidit_controller.rb
class YoudiditController < ApplicationController
  def index
    @challenge = Challenge.find_by(url: 'youdidit')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenge_helper.rb
module ChallengeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/quest2_helper.rb
module Quest2Helper
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/helpers/youdidit_helper.rb
module YoudiditHelper
end

app/views/challenges/show.html.erb
<div id="challenges">
  <h1><%= @challenge.url %></h1>
  <% @challenge.description.split("\n").each do |paragraph| %>
    <p><%= paragraph %></p>
  <% end %>

  <% if @challenge.url == 'TRANSFORMAR' %>
    <div id="imagem-dica">
      <img src="<%= image_path('dica-final.png') %>" alt="dica para resolver o mistério" />
    </div>
  <% end %>

  <div class="formulario-missao">
    <%= form_for challenges_path, method: :patch do |form| %>
      <%= form.text_field :resposta, name: :resposta %>
    <% end %>
  </div>

  <div class="icons">
    <button class="map-icon">
      <img src="<%= image_path('icone-mapa.png') %>" />
    </button>
    <button class="hint-icon">
      <img src="<%= image_path('interroga-icone.png') %>" />
    </button>
  </div>

  <div class="player-counter">
    <h2><%= @challenge.count %></h2>
    <span class="player-counter-text">intrusos</span>
  </div>
</div>

app/views/challenges/update.html.erb
<h1>Challenge#update</h1>
<p>Find me in app/views/challenge/update.html.erb</p>

app/views/home/index.html.erb
<div id="challenges">
  <p>Hey, Hey... você aí... Não acredito, finalmente!!! Alguém me encontrou... Meu nome é Eduardo, eu costumava ser um aluno daqui da Unesp, até que aconteceu... que aconteceu... Bem não lembro direito o que aconteceu, não sei como fiquei preso aqui. Minha memória está dAnIficaDA... preciso descobrir o que aconteceu comigo, por favor, EU PRECISO DE SUA AJUDA!</p>
  <p>Meu inconsciente está querendo se comunicar comigo, ele diz que tem uma forma de desbloquear minhas lembranças. Meus fragmentos de memórias estão espalhados pelo campus, preciso que você vá até a localização e descubra a senha que desbloqueia a próxima memória...1</p>
  <p>A pista que eu tenho é: Vá até Rádio Universitária Unesp FM 105.7, e ache a placa de comemoração dos 30 anos da UNESP FM, nela procure a palavra que complete a frase – “Nos 30 anos da Unesp FM, desejamos que esta árvore aqui plantada inspire nossa luz, nossa água e nossos... ”</p>

  <div class="formulario-missao">
    <%= form_with url: home_guess_path, method: :post do |form| %>
      <%= form.text_field :resposta, name: :resposta %>
      <%= form.hidden_field :id, name: :id, value: @challenge.id %>
    <% end %>
  </div>

  <div class="icons">
    <button class="map-icon">
      <img src="<%= image_path('icone-mapa.png') %>" />
    </button>
    <button class="hint-icon">
      <img src="<%= image_path('interroga-icone.png') %>" />
    </button>
  </div>

  <div class="player-counter">
    <h2><%= @challenge.count %></h2>
    <span class="player-counter-text">intrusos</span>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SemioticaArg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="arg">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/challenge.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SemioticaArg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="challenge-body">
    <div class="arg">
      <%= yield %>
    </div>
  </body>
</html>

app/views/quest2/index.html.erb
<div class="cont-investigadores">
  <span>312</span>
  <p>investigadores</p>
</div>
<p class="descricao-missao">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis.</p>
<div class="formulario-missao">
  <%= form_for quest2_index_path, method: :post do |form| %>
    <%= form.text_field :resposta, name: :resposta %>
  <% end %>
</div>

app/views/quest2/post.html.erb
<h1>Quest2#post</h1>
<p>Find me in app/views/quest2/post.html.erb</p>

app/views/quests/index.html.erb
<h1>Caça ao tesouro da aquário</h1>
<p>Resolva esse mistério e entre pra turma do Scooby Doo</p>
<a href="https://www.google.com/maps/embed/v1/view
  ?key=AIzaSyCrW4q6Rwk9se8Sov6sWlqT70_dVlNbX7o
  &center=-33.8569,151.2152
  &zoom=18
  &maptype=satellite"></a>
<iframe
  width="450"
  height="250"
  frameborder="0" style="border:0"
  referrerpolicy="no-referrer-when-downgrade"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyA6Kj4EqGlAznHmJ53DXAfPsTRdydQ4moI&q=Rádio+Unesp+Fm"
  allowfullscreen>
</iframe>

<%= form_for quests_path, method: :post do |form| %>
  <p>Formulariozinho bala</p>
  <%= form.text_field :resposta, name: :resposta %>
<% end %>

app/views/quests/post.html.erb
<h1>Quests#post</h1>
<p>Find me in app/views/quests/post.html.erb</p>

app/views/youdidit/index.html.erb
<div id="challenges" class="final-screen">
  <p>Todas minhas memórias de quando eu era Eduardo voltaram, estou completo! Minha força está restaurada, agora posso enfrentar minha inimiga e eliminá-la da minha rede!</p>
  <p>Terena teve seu coração corrompido pela ganância, usurpou minha rede e a corrompeu. Ela tem roubado dados e informações de universitários por todo o mundo... não mais! Agora posso combatê-la e restaurar o objetivo do meu projeto.</p>
  <p>Muito obrigado, tudo isso só foi possível graças a você!</p>
  <p>Meu nome agora é EduRoam, minha consciência e a rede se fundiram. Somos um, mas não se preocupe! Estou aqui para fazer segurança de seus dados e facilitar seus estudos! Lembre-se de mim sempre que ligar seu Wi-Fi na Unesp... e se por algum motivo meu sinal cair, é a Terena me atacando, mas não se preocupe, ela não tem mais forças para me derrotar!</p>
  <div class="player-counter">
    <h2><%= @challenge.count %></h2>
    <span class="player-counter-text">intrusos</span>
  </div>
</div>